language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7-dev" # 3.7 development branch

install:
  - pip install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE=LocalizrExample.settings.default

script:
  - python manage.py test